server:
  port: 5001
spring:
  application:
    name: seata-com.cj.account
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: seata
        group: SEATA_GROUP
  datasource:
    dynamic:
      datasource:
        # 设置 账号数据源配置
        account:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/seata_account?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
          username: root
          password: root
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/seata_account?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
          username: root
          password: root
      seata: true # 使用多数据源要让这个属性设为true
seata:
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false  # 使用多数据源设为false ,普通的情况下true
  config:
    type: nacos # nacos 应该是目前比较常用的,以nacos为例子
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      namespace: seata
      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
      group: SEATA_GROUP
      dataId: "seataServer.properties"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: seata
      username: nacos
      password: nacos

feign:
  client:
    config:
      default:
        #不设置connectTimeout会导致readTimeout设置不生效
        connectTimeout: 3000
        readTimeout: 6000