server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #本机ip地址，可不配
  client:
    #表示是否注册自身到eureka服务器， 做集群是设置成true 生产配置为true
    registerWithEureka: false
    #表示是否从eureka服务器获得注册信息，生产配置为true
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
