server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2020_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  #  这个mvc的配置是springboot2.6.1不支持swagger3的折衷配置，后面考虑升级Springboot版本或降级版本
  #  如果你使用的是 Springboot 2.6 版本，需要配置，否则报下面的错   Springboot 3.0 和 Springboot 2.5.8 不需要配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matche



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    #所有entity别名类所在的包


eureka:
  instance:
    prefer-ip-address: true   #访问路径可以显示ip
    instance-id: payment8002
  client:
    #表示是否注册自身到eureka服务器， 做集群是设置成true 生产配置为true
    registerWithEureka: true
    #表示是否从eureka服务器获得注册信息，生产配置为true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

